client_id: "Client1"
train_configs:
  device: "cuda"
  logging_output_dirname: "./output"
  logging_output_filename: "result_flower102_decentralized_ring"

data_configs:
  dataset_path: "./resources/dataset/flower102_decentralized.py"
  dataset_name: "get_flower102"
  dataset_kwargs:
    num_clients: 5
    client_id: 0
    data_path: "/work/mech-ai-scratch/nsaadati/projects/dlora/others/CLIP-LoRA/data/Flower102"
    split: "iid"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False
